### ISSUE TITLE
Refactor typography names

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#150]
Our first approach to create text color utilities used a numeric serie, just like in the Sketch design:

![image](https://user-images.githubusercontent.com/1078228/43950898-f29bd060-9c91-11e8-840d-7d8246e75fe6.png)

**Pros:**
- Independent from theming. Once you know `01` means the main color and the rest is a scale to the complementary one you can implement a dark theme without worrying about semantics.

**Cons:**
- Non semantic. You need to know what `01` to `04` means. Hard to read if you don't.

After talking with @piensaenpixel we thought we should introduce a more semantic naming. We've tried with different combinations and come up with this solution:

![image](https://user-images.githubusercontent.com/1078228/43951076-6d287388-9c92-11e8-962d-9969600d79a8.png)

_Same naming for a light and a dark theme_

The extremes are called `type-primary` and `type-complementary`. In a light scheme, this translates to black and white. In a dark one, to white and black. If you change theme, you won't have to change markup.

We could find any meaningful name for those values in between that works for light and dark themes. For those, we've chosen the first approach, a numeric one.

What do you think @CartoDB/frontend-team ? Any thoughts?

**Comment by VictorVelarde** [comment]
It’s hard to find something semantic, but I think it is worthy. I’ll try to find something related to nearest colors, with an idea of “graduation” eg. something like `type-primary > type-primary-plus > type-secondary-minus > type-secondary`

**Comment by rubenmoya** [comment]
I don't think you can use the graduation approach since the user can set totally different colors, being `primary` red and `primary-plus` dark gray, which it's completely different.

To be honest, I don't see any problem using `$color-[category]-[number]`.

The approach Ivan showed still has the same problem, but now with a mix of semantic naming + numeric naming.

To me the solution would be to keep it as it is, and let the user make it semantic however they want, for example:

```
$color-type-title: $color-type-01;
$color-type-header: $color-type-02;
$color-type-red: $color-type-03;
$color-type-blue: $color-type-04;
```

We should just provide the 4 colors, and let the users decide if they want to use the numeric naming or build something more semantic on top.

**Comment by VictorVelarde** [comment]
IMO that's an important point: is there a graduation idea on those colors or not?

**Comment by piensaenpixel** [comment]
vamos ya
