### ISSUE TITLE
Legends

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#157]
Summoning here @makella 

I know legends are a pending issue in Builder, where we lack the proper way to render several of them. I couldn't find a central place or issue where all the right legends are explained but I recall seeing one of your presentations with a legends list. I remember one with the line thickness, for instance.

It'd be great to start publishing the right legends as components in Airship. Can you provide us with more info in this issue ticket, please, so we can make up our minds about the work to do?

**Comment by makella** [comment]
Yes!

I will compile the tickets here that I know about, and direct you specifically to things that I think we can do better w/ legends.

When will the legend work start? (just to give myself a timeline)

thanks for the ping!

**Comment by ivanmalagon** [comment]
In the next dev cycle we'll continue with Airship. It'll start on September for Airship. There's no need for rush about legends definition. I just want to have a issue to get a grasp on all the work to do with legends and then create the proper issues and prioritize the work from there.

**Comment by makella** [comment]
perfect, thanks, @ivanmalagon! I will start compiling resources and post here over the next week or so.

**Comment by makella** [comment]
hi @ivanmalagon 

There is A LOT of discussion throughout the repos on legends. I linked some of the relevant pieces through my summary below. 

A great place to start is reading this summary of "Legend pains" by @ramiroaznar:
https://github.com/CartoDB/product/issues/35#issuecomment-376550515

I went through and jotted down everything I could think of to improve what we currently have. Sorry if it is a lot and if you need any clarification on any of it, please let me know. 

Once we have a definition of all the map types that we need to cover (assuming carto.js and VL), we can do a cross-check and make sure that we've defined all of them. 

There are also more advanced legend techniques have been implemented into CARTOframes, but I think first, we should make sure we are covering all the basics and then get into the more advanced.

## Points
### Basic representation
In the legend, keep the style properties of the points displayed on the map. For example, if we have a red point symbol that is 20px, with a black outline, the legend should reflect that exact style.

### By value: Color
When symbolizing points by color, we want a point legend :) 
_The only reason I say that is because we have the opportunity to define some different behaviors than what is in Builder._

#### Categories
- Each category symbolized with the appropriate style properties as mentioned under "Basic representation.
  - the style properties are important in this context too because some categories might be symbolized with a white outline and others with a black outline (for example). In addition, a category of point could potentially be larger than other categories. Keeping all of this information (that helps interpret the map) in the legend will be really great.

#### Numbers
- Each class symbolized with a point (the default in Builder is to go to a gradient legend) with the appropriate style properties.
  - For how these stack, I'd say we can keep them vertical as with category legends.
  - For labels, I'm not sure what you guys are thinking but it is useful to have the ranges for each class break. People will want to edit these (because raw values as you know can be ugly), so I think by default, having range labels 

<img width="262" alt="screen shot 2018-08-23 at 1 21 24 pm" src="https://user-images.githubusercontent.com/1566273/44547184-7ff8ee80-a6d7-11e8-8b73-0b7e7815e06d.png">

### Images
- Standard image legend like we have but with the ability to bring the other styling components like size in the legend too.
  - Image markers can be bivariate so one component could represent type (color) and another through size.

### By value: Size
- The biggest thing here for our "bubble legends" is that the sizes of the circles don't match those on the map! This, I think is one of the things I hear most often. 
- Another important thing is that we actually need legends for _two different_ map types especially now that we have interpolation built-in for VL
  - **classed maps**
    - here, similar to the colored points legend, we will want each class break's circle size in the legend with the associated range. A lot of the legends for this kind of map are very similar to what we used to have in Editor:
<img width="711" alt="screen shot 2018-08-23 at 1 56 04 pm" src="https://user-images.githubusercontent.com/1566273/44548796-54c4ce00-a6dc-11e8-8662-f208a0aeb7ee.png">
  - **unclassed maps** 
    - A really great paper (written by a famous cartographer)
  - https://www.researchgate.net/publication/220144157_Self-Adjusting_Legends_for_Proportional_Symbol_Maps
  - on the first page, you will see a list of requirements
- There was discussion in the past, but it never went anywhere. This would be a big win for us!
  - https://github.com/CartoDB/design/issues/639#issuecomment-285369477

## Lines
### Basic representation
Let's have lines in the legend! You can see some work @elenatorro has been doing with VL legends and what a difference it makes
 - https://github.com/CartoDB/carto-vl/pull/869#issuecomment-414722770
Similar to the comments above for points, we should keep the style properties of the lines on the map. 
### By value: Color
#### Numbers and Categories
Follow similar guidelines for color by value in the points section. Also bring in additional style properties from the map.
- for example, see @ramiroaznar example here https://github.com/CartoDB/design/issues/477)

### By value: Size
We've had a lot of discussion about a sized line legend and even mock-ups! You can see those and the discussion here: https://github.com/CartoDB/design/issues/296

- Similar to points, we will have classed and unclassed lines. 
  - For the classed lines, we can do the horizontal legend where you see each class break:
<img width="262" alt="screen shot 2018-08-23 at 2 07 28 pm" src="https://user-images.githubusercontent.com/1566273/44549318-f567bd80-a6dd-11e8-8df3-d15f3cdced35.png">

  - for unclassed, we would likely expect to see something more like this one:
<img width="258" alt="screen shot 2016-10-26 at 9 02 19 am" src="https://cloud.githubusercontent.com/assets/1566273/19731724/9e808ffe-9b5b-11e6-928a-be25201f77f0.png">

### By value: size and color
- Combining size and color combinations
  - think of road types colored and sized differently but condensed into one legend (vs. the two that you get currently w/ Builder)

## Polygons
### Basic representation
- Let's use squares for the legend!
- Let's take over the styling properties to the legend!

### Style by value: color
### Style by value: numbers
Similar to points and lines, we will need two legend types
  - Classed maps 
    - traditionaly, you see color chips for each class (like we used to have in Editor)
<img width="372" alt="screen shot 2018-08-23 at 2 17 54 pm" src="https://user-images.githubusercontent.com/1566273/44549794-6d82b300-a6df-11e8-8d07-3e9452d3bf91.png">
    - there were other mock-ups for Builder that were more along the lines of a traditional classed map legend, so we might be able to use some of those https://github.com/CartoDB/cartodb/issues/9051
    
  - Unclassed maps 
    - the gradient legend that we currently have is more suited for this map type since the colors are ramped from start to end along all of the values in the data
<img width="638" alt="screen shot 2018-08-23 at 2 22 00 pm" src="https://user-images.githubusercontent.com/1566273/44549950-ff8abb80-a6df-11e8-971e-cc87e8437ba7.png">

**Comment by makella** [comment]
cc'ing @elenatorro for visibility as she has been working on `getLegend()` for VL. Some of the things that we want to add for legends there we are thinking will be part of Airship. 

@elenatorro if I have missed anything, please feel free to add.

@ramiroaznar you too!!

**Comment by ivanmalagon** [comment]
I'm revisiting this ticket to come up with actual tickets and I have a doubt about point legends by size.

Would this design fit both classed and unclassed maps?

![image](https://user-images.githubusercontent.com/1078228/46728334-dff52580-cc82-11e8-8a40-e2a95ed3d0c6.png)

I think this solution (based on your suggestion in other ticket) would fit the case where the actual sizes are pretty small. But I don't know if it can used for both kind of maps.

**Comment by jorgesancha** [comment]
Hey @andy-esch could you check the legends above and see if you miss any specific ones for CARTOframes. Also, if you can point it which ones are the most important ones from your point of view, that'd be great

**Comment by andy-esch** [comment]
After speaking with @makella, this seems like a minimum viable set for legends:
+ numeric color with class breaks (points, lines, polygons)
+ continuous color (points, lines, polygons)
+ category (points, lines, polygons)
+ size with class breaks (points, lines)
+ continuous size (points, lines)

**Comment by jorgesancha** [comment]
Using this issue as the meta issue for Legends.

These are the first set of legends we aim to cover first, each with their individual issues for tracking comments

- [ ] Simple / Categorical (Point, Line, Polygon, Marker)
- [ ] Point size, classed
- [ ] Point size, unclassed
- [ ] Line size, classed
- [ ] Line size, unclassed
- [ ] Polygon color, classed (color steps)
- [ ] Polygon color, unclassed (gradient)
- [ ] Bivariants Choropleths (square grid)

This is the working document: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

@kukukaka as discussed. We can make progress but we'll need design's help for the look and feel.

**Comment by andy-esch** [comment]
I don't know if this the best place to leave this comment, but I've done some thinking about the display of numbers on legends and want to make sure it helps inform the dev/design process. From https://github.com/CartoDB/cartoframes/issues/544:

> In cartoframes vl, values should be in scientific notation, i.e., `1.5e-3 - 2.5e-3` so we can avoid mistakes like I made when i just rounded to two values. We can have numbers that are less than 0.01 but still be very meaningful. E.g., if the data range is 0.00001 to 0.006 we need to ensure the legend displays that data meaningfully.

> <img width="157" alt="screen shot 2019-02-26 at 10 05 18 am" src="https://user-images.githubusercontent.com/1041056/53422845-423e9080-39ae-11e9-9243-e8aff079db0d.png">

**Comment by Lady-Aga** [comment]
Now I'll put the legends in each corresponding issue (as well as some doubts I have), but this is an image of how they are for now.

![347 - Legends](https://user-images.githubusercontent.com/49977486/57137142-3c4e9c80-6daf-11e9-86dd-b8cd28353c8e.png)

**Comment by Lady-Aga** [comment]
Hello!

@makella and I have moved forward on Legends design!
Here is an InVision with the Legends and two examples of them in a Jupyter Notebook layout (with and without scroll).

Cheers!

https://projects.invisionapp.com/share/9SRXFRLQTMP#/screens

**Comment by andy-esch** [comment]
Beautiful!!!

One quick question: How do you envision negative numbers appearing in the ranges? E.g,. `-20 - -30`? Will the separator be wider than the negative symbol?

**Comment by makella** [comment]
good point, @andy-esch 

@newLadyAga taking a closer look and based on andy's comments, two things:
#### General spacing between ranges and dash
- we probably want to put a space between the end of a number, the dash, and the beginning of the next number. 
    - I see that in the classed polygon range labels: 
    <img width="167" alt="Screen Shot 2019-05-14 at 10 22 58 AM" src="https://user-images.githubusercontent.com/1566273/57714736-610a0600-7632-11e9-86ea-eec55657e66a.png"> . 
    - but not in the classed line range labels:
    <img width="167" alt="Screen Shot 2019-05-14 at 10 22 40 AM" src="https://user-images.githubusercontent.com/1566273/57715025-0624de80-7633-11e9-9e29-c2340297fdac.png">

    - or the classed point range labels:
    <img width="167" alt="Screen Shot 2019-05-14 at 10 31 11 AM" src="https://user-images.githubusercontent.com/1566273/57715269-96fbba00-7633-11e9-8f01-476c0e54bed4.png">

Are there constraints with the latter two for the space? 

#### Treatment of negative numbers and range labels:
-  I see two options (with either one we will probably need to take a second look at alignment, but just for a quick reference):
    - as @andy-esch mentions, using an em dash: 

    <img width="140" alt="Screen Shot 2019-05-14 at 10 48 14 AM" src="https://user-images.githubusercontent.com/1566273/57716349-070b3f80-7636-11e9-94e0-cfcc5102eb8c.png">

    - or another common alternative is to replace the range dash with the word `to`:
    
<img width="132" alt="Screen Shot 2019-05-14 at 10 49 12 AM" src="https://user-images.githubusercontent.com/1566273/57716476-56517000-7636-11e9-877e-f8cce4646414.png">

**Comment by newLadyAga** [comment]
Thank you for your comments, @andy-esch and @makella!

Yes, I think is a good idea to put a space on both sides of the dash, as it improves the readability a lot and there aren't space constraints.

Regarding the treatment of negative numbers and range labels, I find interesting the dash replacement with the word "to". Since the font size on labels is quite small I think this variation would be clearer. Do you like it too, @andy-esch?

**Comment by makella** [comment]
hiii @newLadyAga I think @andy-esch is out of the office for a few days. if you think the "to" makes sense, let's go ahead with that idea and see how it would look in the mocks.

let me know if there is anything i can do to help! 

thanks!

**Comment by newLadyAga** [comment]
Perfect, @makella!

Let's try then what the separate ranges look like with the "to". I think they work well for both positive and negative numbers.

Let me know your thoughts!
Thank you!

![ranges separated with TO](https://user-images.githubusercontent.com/49977486/57932178-9cb70100-78ba-11e9-9f6a-a7b5bbfb48af.png)

**Comment by kukukaka** [comment]
I would try to avoid using "to". I think we should try to avoid as much as possible English in non-customizable strings of any Airship module if we have other options language agnostic.

**Comment by newLadyAga** [comment]
Yes, it makes sense. We have to use a dash then. 

After a few searches I found that the most appropriate representation for ranges would be to use an "em dash" without spaces, however, I think this solution doesn't work well with negative values, even if the dash has a softer color.

I put the tests here. I would opt for the third one, with space between the values and the dash and all the text in the same color.

![ranges separated with EM DASH](https://user-images.githubusercontent.com/49977486/58017821-71722300-7b01-11e9-881b-ee374bdd3527.png)

![ranges separated with spaced EM DASH ](https://user-images.githubusercontent.com/49977486/58017812-69b27e80-7b01-11e9-8dca-63c6e817fa17.png)

![ranges separated with spaced EM DASH same color](https://user-images.githubusercontent.com/49977486/58017779-57d0db80-7b01-11e9-80d3-1d2053d58b64.png)

**Comment by newLadyAga** [comment]
Hi!

Nice to see a real-world example!

Yes, definitely the simple dash isn't working well with negative numbers.

I also think we were gonna go with the EM Dash. 

This is a test with the EM Dash in bold, to see if it helps visualize it even better.

Thank you!

![ranges separated with spaced EM DASH BOLD same color](https://user-images.githubusercontent.com/49977486/64858030-89c4fb00-d626-11e9-89aa-6255879d93d3.png)

**Comment by VictorVelarde** [comment]
@elenatorro Let's keep this in mind, in case we fix anything more in the library. If we don't have that need soon, we can always derive this to RT.

**Comment by ivanmalagon** [comment]
Can we close this issue? It's been inactive for more than one year

(I'm cleaning up my GitHub open issues)

**Comment by jorgesancha** [comment]
🖖

**Comment by ramiroaznar** [comment]
:rocket:

**Comment by rjimenezda** [comment]
🔥

**Comment by VictorVelarde** [comment]
I have talked about Legends this morning.... just saying 😛 

(💋  💋  to everyone involved here)
