### ISSUE TITLE
Tabs are not well rendered when there is long content

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#167]
![bad tabs](https://user-images.githubusercontent.com/1078228/44350452-afbdb180-a49f-11e8-8c18-dc05b94e6c3e.gif)

When content in tabs exceeds one line, the hover highlight in single line tabs is rendered wrongly.

**Comment by rubenmoya** [comment]
I've seen that earlier, I'm pretty sure it only happens when using the responsive views in Catalog, not sure why

**Comment by jesusbotella** [comment]
Nope, it happens in every mobile view due to `align-items: center`. We should change it to `align-items: baseline` to have them all aligned to bottom when any element has more than one line of text.

It'll look like this:
![screen shot 2018-09-03 at 11 57 05](https://user-images.githubusercontent.com/4319728/44980670-d46e5a80-af70-11e8-9fb8-08c60748b31a.png)

What do you think @piensaenpixel?

**Comment by jesusbotella** [comment]
After talking with @piensaenpixel, we noticed that the horizontal scroll was missing. So, now it works as expected. I attach a GIF working in Chrome Mobile simulator (that's why doesn't have hover states):

![scroll](https://user-images.githubusercontent.com/4319728/45026889-0dc1cb80-b040-11e8-865d-ab4e8e01efdd.gif)
