### ISSUE TITLE
npm package has a wrong version

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#177]
We published a version with a wrong prerelease number, `1.0.0-alpha-27.0`. It should've been `1.0.0-alpha.27`.

It's preventing the registry from delivering the latest alpha. Instead of serving `1.0.0-alpha.34`, it still serves the wrong one.

I guess it'll be overcome when we reach beat but if we could fix it in the alpha, the better.

**Comment by jesusbotella** [comment]
I read [this article](https://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) regarding NPM package and it is no longer possible to unpublish any package release older than 24 hours, like ours.

I tried to execute `npm unpublish @carto/airship-style@1.0.0-alpha-27.0`, just in case there was any possibility but it throwed this error:
```
npm ERR! unpublish Failed to update data
npm ERR! code E400
npm ERR! You can no longer unpublish this version. Please deprecate it instead
npm ERR! npm deprecate @carto/airship-style@1.0.0-alpha-27.0 "this version has been deprecated" : 17-a9a01cebb653eb3c758a078d3a07125b
```

It tells us to deprecate the version instead of unpublishing it, but we have already done that and it continues telling that the newest version is the deprecated one, so 🤷‍♂️ 

I have just contacted npm support and I'll keep you posted about what they'll tell me.

**Comment by ivanmalagon** [comment]
How is this going with npm?

**Comment by jesusbotella** [comment]
After rochoa's mail, they told this to us:
```
Hi Raul,

Thanks for following up. I'm afraid it will take us a little longer than expected to unpublish this version.

I'll follow up when our team has it taken care of.

Thanks for your patience with this issue.
```

**Comment by jesusbotella** [comment]
npm has successfully deleted `@carto/airship-styles@1.0.0-alpha-27.0`. So now, latest version is 1.0.0 and we have a prerelease version (1.0.0-alpha.37) as well.

🎉
