### ISSUE TITLE
Category widget issues

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#192]
- [x] Category widget example has a syntax error, is missing a comma in the values
- [x] Category widget shouldn’t have padding
- [x] Category widget button doesn’t have any styles

**Comment by rubenmoya** [comment]
About the selected items count and clear button, IMHO we shouldn't give that to the users, we should give them the methods to achieve that but no UI since that will require a lot of work in our side to show/hide it and customize it.

It's really easy to add an airship button which calls `widget.clearSelected()`, but it's not as easy to add the airship button styles to the widget, allow them to be overridden, give a slot so the users can use a custom element or translation, add methods to show it and hide it...

I think we should remove the footer in both, this widget and the histogram one, and let the users decide how to do it.
