### ISSUE TITLE
Histogram issues

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#205]
#### Format axis

![image](https://user-images.githubusercontent.com/1078228/44548056-48ad3080-a71d-11e8-84a8-56c305b5cd43.png)

Numbers on axis should be formatted to avoid getting numbers overflown.

#### Back to black

When selecting a range and then clearing the selection, the button gets black.

![back to black](https://user-images.githubusercontent.com/1078228/44663144-fcf5d200-aa0f-11e8-824c-d049be749f37.gif)

**Comment by rjimenezda** [comment]
So I sort of fixed this, but then @alexsroth pointed out that it sometimes doesn't look that great either.

Case in point:

![image](https://user-images.githubusercontent.com/446970/44595435-34bf0880-a7c9-11e8-9497-0c36c898760e.png)

We should probably play with d3-axis which in turn uses d3-format, to get an acceptable number format that's not too long.

**Comment by jesusbotella** [comment]
Regarding back to black, we set the `:focus` to the same color as the active one so that was the issue. If we want to differentiate the focus state, I'd put an outline like browsers do.

![histogrambutton](https://user-images.githubusercontent.com/4319728/44667756-f40afd80-aa1b-11e8-8ff1-bcd21338e585.gif)

**Comment by jesusbotella** [comment]
Fixed!
