### ISSUE TITLE
Add responsive option to widgets

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#454]
**Problem**
When the viewport size changes the widget keep their original size leading to bad UX.

**Proposed solution**
Add a new `responsive` boolean parameter to all the widgets. When this flag is set to true, the widget will be re-rendered when the [resize](https://developer.mozilla.org/en-US/docs/Web/Events/resize) event is fired.

```html
<as-widget responsive>
</as-widget>
```

**Comment by ivanmalagon** [comment]
Responsive should be `true` by default. Think of a tablet user that switch from portrait to landscape.

Check in this issue also if the resize affects also to other style elements. I'm pretty sure than the answer is no because layout elements are based on particular widths and height but check it, please.
