### ISSUE TITLE
Histogram selectionChanged triggered on data changes

### ISSUE THREAD

**Issue by rochoa** [CartoDB/airship#525]
**What is happening?**
When having a histogram associated with a CARTO VL layer and you apply a filter from the histogram,  the data in the layer changes and the data in the histogram gets updated, at that moment the histogram fires another `selectionChanged` event, however, the selection didn't change, the only thing that changed was the data.

**What should happen?**
The selectionChanged should not be triggered. To be more precise, the selection should not change when the data changes.

**Steps to Reproduce**
https://bl.ocks.org/rochoa/raw/4deebb89f4f101cd47e5c43fd843d36c/

**Comment by rjimenezda** [comment]
Ok, this is kind of a big deal. I've been going at this for a while so let me write my findings down. Spoiler alert: I don't really have a solution right now.

---

You're absolutely right. We should not trigger `selectionChanged` when we're updating the data.

The reason why it's triggering is because every time we need to repaint the histogram (i.e. updating the data), the selection is adjusted to snap to the nearest bins. Each and one of these adjustments triggers an event, which updates the Viz, which updates the data, and so on, so chaos ensues.

It was tricky, but I was able to set up a flag when data is updated to 'mute' the event emitting. Now the event won't be triggered, so :+1:

Still, there's something funny going on with the selection:

![selection](https://user-images.githubusercontent.com/446970/48863301-3ba9e700-edc9-11e8-9510-c1fae5aa7af8.gif)

The filtering works, but the selection is totally wrong. I'm selecting (roughly) from 0 to 500k, and the X-axis reflects it properly, but the selection is much lower at the end, why?

The reason is the same as above. `blendTo` causes several repaints, so in the beginning the data interval is roughly [0, 2.5M], and will change to [0, 500k] in regular intervals. 
For each one of these intervals a repaint is required, so we naturally adjust the selection. The problem is, the bins of the histogram are changing so now in the new range of [0, 2M], our 500k maybe falls on a lower bin, so we adjust it to 430k, and so on and so on. By the end, the selection has been reduced to [0, ~100k], without triggering any events.

Naturally, if we blend with 0 duration, this doesn't happen:

![selection2](https://user-images.githubusercontent.com/446970/48864035-a2c89b00-edcb-11e8-8982-495210b0c006.gif)

But we should be able to blend with whatever we want.

Side note: 

As we already knew, the 'dummy' nature of the histogram means that it just represents whatever you're providing, so if you filter and provide the output of the filtered data, it turns into the whole X-Axis, and from there you can only restrict it more and more, or reset.

I think the solution for the first GIF is acceptable, but we have to figure out a way of dealing with the selection adjustment on all possible cases:

- When the user is dragging the selection.
- When a data update comes (map being dragged).
- When a batch of data updates come (blending).

**Comment by ivanmalagon** [comment]
Talked with Roman about this.

There is stuff going on on the two libraries, Airship and CARTO VL. Let me start by VL and correct me if I'm wrong or we're getting the wrong idea about how it works.

As Roman told in the previous comment, when we filter we receive a lot of updates with the intermediate steps until the data correspond to the desired filter. Those fades are there because of visualization reasons but they're not the data we're looking for.

If I filter my column `price` by the range [10, 30] from a total of [0, 50], I want that data and not an animation of the data where some values out of that range are fading [5, 42], [7, 36] and finally [10, 30], for instace. What I'm receiving is the visualization info.

Perhaps there's a way to be notified when the filter operation finish and we didn't find it. The promise returned by `blendTo` seems to resolve when it validates the operation but not when the blend is over.

Regarding Airship, Roman explains it very well in the comment above. We're trying the histogram to be smart in that situation of values changing over time to guess when it's finished but we don't know yet how brittle the solution will be. That's a job on our part. But we think that the mixture of pure data and visualization data can bring problems to other integrations as well. They'll run into the same problem.

Correct us if we're wrong. If you agree, I can open a ticket on VL repo to not forget about this issue. Righ off the bat, a solution on the VL side would be to indicate somehow (event, promise, ...) that the filtering has finished but we don't know the implication with other parts of the library.

**Comment by VictorVelarde** [comment]
How about using a debounced version of `updateWidgets` function?
That pattern is used in several CARTO VL tests, as the way to deal with consequent `blendTo` updates

**Comment by rochoa** [comment]
I don't think having a promise like that will help. If your layer is animated, the promise will never resolve, making impossible to determine the data finally changed.

Some random thoughts:
1. In Airship, what about removing the selection when the data changes? If the new buckets don't match exactly with the previous ones, you are misleading the user.
1. I didn't think about the alternative proposed in the previous point from the programmatic point of view: I could call the `clearSelection` method when the data changes.
1. To avoid this behaviour, I used the following trick: make CARTO VL to always return the same amount number of buckets with the very same ranges. With that, the previously selected range always makes sense. I'm gonna open a PR in CARTO VL to incorporate this at the API level of the `viewportHistogram` expression.
