### ISSUE TITLE
Legend component: Line size, unclassed

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#587]
Line size, unclassed, part of #157 :

![image](https://user-images.githubusercontent.com/86218/55346267-62cc9f80-54b2-11e9-96b9-db5f78c45a3b.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
![587 - Line size, unclassed](https://user-images.githubusercontent.com/49977486/57137588-9c920e00-6db0-11e9-86ce-403a04b7a158.png)

**Comment by makella** [comment]
@Lady-Aga here, how many representative line weights do you think we should take? Since the lines are unclassed, there will be unique line weights for each line in the data. A common practice with unclassed legends is to take some representative sample values to provide a point from which users can interpret the symbology on the map. More than anything, just curious about your thoughts on this.

**Comment by makella** [comment]
similar to unclassed point size, where do you envision values being placed vs. the low to high text?
