### ISSUE TITLE
Basic CSS: typography

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#76]
Reference:
- https://projects.invisionapp.com/share/3REYL6RJK#/screens/269307387

### TYPOGRAPHY

Typefont: Roboto, Overpass

#### Jumbo

![image](https://user-images.githubusercontent.com/1078228/42952087-f7c78794-8b77-11e8-8156-42fdbf6dee15.png)

#### Display

![image](https://user-images.githubusercontent.com/1078228/42952131-0c26bba6-8b78-11e8-907d-8769e229c7ba.png)

#### Title (Regular / Medium)

![image](https://user-images.githubusercontent.com/1078228/42952179-301c3978-8b78-11e8-986e-eb35b7fb27a0.png)

#### Subheader (Regular / Medium / Mono)

![image](https://user-images.githubusercontent.com/1078228/42952211-41c69416-8b78-11e8-8e18-9f8436c8fa73.png)

#### Body (Regular / Medium / Mono)

![image](https://user-images.githubusercontent.com/1078228/42952370-9b80ba68-8b78-11e8-9322-141fe576af26.png)

#### Caption (Regular / Medium / Mono)

![image](https://user-images.githubusercontent.com/1078228/42952600-223858fe-8b79-11e8-98e6-0583cd9f55c4.png)

#### Lists

![image](https://user-images.githubusercontent.com/1078228/42952602-2263f978-8b79-11e8-970d-ad12cdf79655.png)

**Comment by rubenmoya** [comment]
I was trying to create the list element, and I realized that since we use a reset to remove all margins and paddings right now the content looks pretty bad:

![screen shot 2018-08-01 at 09 43 07](https://user-images.githubusercontent.com/905225/43508177-7acd15e0-956f-11e8-8503-b60a981222bf.png)

There is no separation between titles, paragraphs, lists, etc

I see two approaches here:
- Think again if we should reset everything (or maybe we could use something less agressive like normalize)
- Talk with design to add a margin/padding to the elements that need it (headings, paragraphs and lists for now)

**Comment by piensaenpixel** [comment]
+1 to 'Talk with design to add a margin/padding to the elements that need it (headings, paragraphs and lists for now)'
